language: python
env:
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.4.x.zip
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.7.x.zip
  - DJANGO_VERSION=https://github.com/django/django/archive/stable/1.8.x.zip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=https://github.com/django/django/archive/stable/1.4.x.zip
     - python: "3.4"
       env: DJANGO_VERSION=https://github.com/django/django/archive/stable/1.4.x.zip
     - python: "2.6"
       env: DJANGO_VERSION=https://github.com/django/django/archive/stable/1.7.x.zip
     - python: "2.6"
       env: DJANGO_VERSION=https://github.com/django/django/archive/stable/1.8.x.zip
install:
  - pip install django==$DJANGO_VERSION nose --use-mirrors
  - pip install . --use-mirrors
script:
  - nosetests tests/tests.py