language: python
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.2
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=1.4.10
     - python: "3.4"
       env: DJANGO_VERSION=1.4.10
  allow_failures:
     - python: "3.4"
install:
  - pip install django==$DJANGO_VERSION nose --use-mirrors
  - pip install . --use-mirrors
script:
  - nosetests tests/tests.py