language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=1.4
     - python: "3.4"
       env: DJANGO_VERSION=1.4
     - python: "2.6"
       env: DJANGO_VERSION=1.7
     - python: "2.6"
       env: DJANGO_VERSION=1.8
install:
  - pip install django==$DJANGO_VERSION nose --use-mirrors
  - pip install . --use-mirrors
script:
  - nosetests tests/tests.py