language: python
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.4
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy3"
  - "pypy"
matrix:
  exclude:
     - python: "2.6"
       env: DJANGO_VERSION=1.7
     - python: "2.6"
       env: DJANGO_VERSION=1.8
     - python: "2.6"
       env: DJANGO_VERSION=1.9
     - python: "2.6"
       env: DJANGO_VERSION=1.10
     - python: "2.6"
       env: DJANGO_VERSION=1.11
     - python: "3.3"
       env: DJANGO_VERSION=1.4
     - python: "3.3"
       env: DJANGO_VERSION=1.9
     - python: "3.3"
       env: DJANGO_VERSION=1.10
     - python: "3.3"
       env: DJANGO_VERSION=1.11
     - python: "3.4"
       env: DJANGO_VERSION=1.4
     - python: "3.5"
       env: DJANGO_VERSION=1.4
     - python: "3.5"
       env: DJANGO_VERSION=1.5
     - python: "3.5"
       env: DJANGO_VERSION=1.6
     - python: "3.5"
       env: DJANGO_VERSION=1.7
     - python: "3.6"
       env: DJANGO_VERSION=1.4
     - python: "3.6"
       env: DJANGO_VERSION=1.5
     - python: "3.6"
       env: DJANGO_VERSION=1.6
     - python: "3.6"
       env: DJANGO_VERSION=1.7
     - python: "pypy3"
       env: DJANGO_VERSION=1.4
     - python: "pypy3"
       env: DJANGO_VERSION=1.9
     - python: "pypy3"
       env: DJANGO_VERSION=1.10
     - python: "pypy3"
       env: DJANGO_VERSION=1.11
install:
  - pip install -r test-requirements.txt
  - pip install "django==$DJANGO_VERSION.*"
  - pip install -e .
script:
  - py.test --cov=djpj tests/tests.py
after_success:
  - coveralls
